services:
  tensorflow:
    image: lsmliborio/tensorflow:2.17.0.3-gpu
    container_name: tensorflow
    runtime: nvidia
    volumes:
      - ./:/workspace
      - ./mlruns:/mlruns      
      - /mnt/e/datasets/:/workspace/datasets

    ports:
      - "4040-4050:4040-4050"
      - "5000:5000"
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - MLFLOW_TRACKING_URI=file:///mlruns
    command: >
      mlflow server
      --backend-store-uri file:///mlruns
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5000
