services:
  tensorflow:
    image: lsmliborio/tensorflow:2.17.0.3-gpu
    volumes:
      - ./:/workspace
      - ./mlflow_data:/mlflow_data                   
    ports:
      - "4040-4050:4040-4050"                        # pyspark
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 # pyspark
      - MLFLOW_TRACKING_URI=http://mlflow:5000       # mlflow service
    command: tail -f /dev/null
    runtime: nvidia

# comentar caso não queira utilizar mlflow
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.3
    volumes:
      - ./mlflow_data:/mlflow_data
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow_data/mlflow.db
      --default-artifact-root /mlflow_data/artifacts
      --host 0.0.0.0
      --port 5000