# imagem bruta, sem pyspark e afins
services:
  tensorflow:
    image: lsmliborio/tensorflow:2.17.0.2 # 2.14.0.7-gpu 2.17.0.2
    volumes:
      - ./:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: tail -f /dev/null
    runtime: nvidia